apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-app-deployment
  labels:
    app: search-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: searchapp
  template:
    metadata:
      labels:
        app: searchapp
    spec:
      containers:
      - name: search-app-deployment
        image: phanha/searchapp
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000