apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-search-app-linux-deployment
  namespace: eks-search-app
  labels:
    app: eks-search-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-search-app-linux-app
  template:
    metadata:
      labels:
        app: eks-search-app-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.23
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
