apiVersion: v1
kind: Service
metadata:
  name: eks-search-app-linux-service
  namespace: eks-search-app
  labels:
    app: eks-search-linux-app
spec:
  selector:
    app: eks-search-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80